
spring:
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movie/**
          filters:
            - AuthenticationFilter




        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8070/eureka/